const UPDATE_TICKER = 'UPDATE_TICKER/ticker';
const UPDATE_TICKER_SUCCESS = 'UPDATE_TICKER_SUCCESS/ticker';
const UPDATE_TICKER_FAILED = 'UPDATE_TICKER_FAILED/ticker';
const UPDATE_BOOK = 'UPDATE_BOOK/ticker';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS/ticker';
const UPDATE_BOOK_FAILED = 'UPDATE_BOOK_FAILED/ticker';

export default {
  UPDATE_TICKER,
  UPDATE_TICKER_SUCCESS,
  UPDATE_TICKER_FAILED,
  UPDATE_BOOK,
  UPDATE_BOOK_SUCCESS,
  UPDATE_BOOK_FAILED,
};
