const UPDATE_TICKER = 'UPDATE_TICKER/ticker';
const UPDATE_TICKER_SUCCESS = 'UPDATE_TICKER_SUCCESS/ticker';
const UPDATE_TICKER_FAILED = 'UPDATE_TICKER_FAILED/ticker';
const GET_BOOK = 'GET_BOOK/ticker';
const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS/ticker';
const GET_BOOK_FAILED = 'GET_BOOK_FAILED/ticker';

export default {
  UPDATE_TICKER,
  UPDATE_TICKER_SUCCESS,
  UPDATE_TICKER_FAILED,
  GET_BOOK,
  GET_BOOK_SUCCESS,
  GET_BOOK_FAILED,
};
